name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check Lint workflow
        run: |
          conclusion=$(gh run list --repo zacharyarnaise/heim --workflow=Lint --branch=main --limit=1 --json conclusion --jq '.[0].conclusion')
          if [ "$conclusion" != "success" ]; then
            echo "Skipping update, lint is currently failing."
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035
        with:
          nix_on_tmpfs: true

      - name: Cache Nix store paths
        uses: nix-community/cache-nix-action@135667ec418502fa5a3598af6fb9eb733888ce6a
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1073741824
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never

      - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd
        with:
          ssh-private-key: ${{ secrets.PK }}

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@834c491b2ece4de0bbd00d85214bb5e83b4da5c6
        with:
          pr-title: "chore(lock): update"
          pr-reviewers: zacharyarnaise
          git-author-name: "Zachary Arnaise"
          git-author-email: "121795280+zacharyarnaise@users.noreply.github.com"
          git-committer-name: "Zachary Arnaise"
          git-committer-email: "121795280+zacharyarnaise@users.noreply.github.com"
